"""
Django settings for KG_backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read configuration from environment (with a project-root .env if present).
# All deployment-specific values live in the environment, never in source.
env = environ.Env()
environ.Env.read_env(BASE_DIR.parent / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
# The default below is for local development ONLY; production must set
# DJANGO_SECRET_KEY in the environment (the old committed key is rotated out).
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-DEV-ONLY-do-not-use-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files in production (DEBUG off).
    # Must sit directly after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# CORS: wide open only in local development. In production, restrict to the
# known frontend origin(s) via DJANGO_CORS_ORIGINS (comma-separated).
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = env.list('DJANGO_CORS_ORIGINS', default=[])

ROOT_URLCONF = 'KG_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KG_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Env-switchable via DATABASE_URL: defaults to local SQLite for development,
# set e.g. postgres://user:pass@host:5432/db in production.
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic target; WhiteNoise serves these when DEBUG is off.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Per-car image assets (svg/png/etc referenced from manual HTML content).
# Each car gets a folder named exactly after its db file, e.g.
# static_warehouse/Corolla Cross Hybrid S/<file>, served at /media/<car>/<file>.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'static_warehouse'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Security hardening — applied when DEBUG is off. SSL-dependent flags are
# gated behind DJANGO_SECURE_SSL so http-only internal deployments still work.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    _secure_ssl = env.bool('DJANGO_SECURE_SSL', default=False)
    SESSION_COOKIE_SECURE = _secure_ssl
    CSRF_COOKIE_SECURE = _secure_ssl
    SECURE_SSL_REDIRECT = _secure_ssl
    SECURE_HSTS_SECONDS = 31536000 if _secure_ssl else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _secure_ssl
    SECURE_HSTS_PRELOAD = _secure_ssl
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Logging — structured console output to stdout (captured by the container
# runtime / process manager). Level via DJANGO_LOG_LEVEL.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': env('DJANGO_LOG_LEVEL', default='INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
