# Generated by Django 5.2.3 on 2026-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField()),
                ('year', models.IntegerField()),
                ('db_address', models.TextField()),
            ],
            options={
                'db_table': 'main_db',
            },
        ),
    ]
