# Generated by Django 5.2.3 on 2026-06-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
