# Generated by Django 6.0.6 on 2026-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_car_car_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=120)),
                ("model", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=20)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("company", models.CharField(max_length=200)),
                ("landline", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=40)),
                (
                    "reg_no",
                    models.CharField(max_length=60, verbose_name="registration number"),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("handled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
