# Generated by Django 6.0.6 on 2026-07-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_purchaserequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("reg_no", models.CharField(blank=True, default="", max_length=60)),
                ("landline", models.CharField(blank=True, default="", max_length=40)),
                ("mobile", models.CharField(blank=True, default="", max_length=40)),
                ("employees_count", models.PositiveIntegerField(blank=True, null=True)),
                ("seats_count", models.PositiveIntegerField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("ai_assistant_enabled", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="employees_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="seats_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "جدید"),
                    ("reviewing", "در حال بررسی"),
                    ("approved", "تأیید شده"),
                    ("rejected", "رد شده"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="wants_ai_assistant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="wants_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PortalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password_hash", models.CharField(max_length=256)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("after_sales_manager", "مدیر خدمات پس از فروش"),
                            ("after_sales_head", "رئیس خدمات پس از فروش"),
                            ("technical_expert", "کارشناس فنی"),
                            ("after_sales_supervisor", "سرپرست خدمات پس از فروش"),
                            ("technical_staff", "پرسنل خدمات فنی"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ai_assistant_enabled", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name", "username"],
            },
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api.portaluser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60)),
                ("detail", models.CharField(blank=True, default="", max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.portaluser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyCarAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documents", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="api.car",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_accesses",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "car")},
            },
        ),
        migrations.CreateModel(
            name="UserCarAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documents", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="api.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_accesses",
                        to="api.portaluser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "car")},
            },
        ),
    ]
