# Generated by Django 6.0.6 on 2026-07-05 06:56

import django.db.models.deletion
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def remap_legacy_roles(apps, schema_editor):
    PortalUser = apps.get_model('api', 'PortalUser')
    mapping = {'technical_expert': 'after_sales_specialist', 'technical_staff': 'after_sales_specialist'}
    for old, new in mapping.items():
        PortalUser.objects.filter(role=old).update(role=new)


def seed_platform_admin(apps, schema_editor):
    PlatformAdmin = apps.get_model('api', 'PlatformAdmin')
    if not PlatformAdmin.objects.filter(username='admin').exists():
        PlatformAdmin.objects.create(
            username='admin',
            password_hash=make_password('admin'),
            active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_company_purchaserequest_employees_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password_hash", models.CharField(max_length=256)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="department_label",
            field=models.CharField(default="خدمات پس از فروش", max_length=80),
        ),
        migrations.AddField(
            model_name="portaluser",
            name="access_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portaluser",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercaraccess",
            name="admin_granted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(remap_legacy_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="portaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("after_sales_manager", "مدیر خدمات پس از فروش"),
                    ("after_sales_head", "رئیس خدمات پس از فروش"),
                    ("after_sales_supervisor", "سرپرست خدمات پس از فروش"),
                    ("after_sales_specialist", "کارشناس خدمات پس از فروش"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="AdminAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api.platformadmin",
                    ),
                ),
            ],
        ),
        migrations.RunPython(seed_platform_admin, migrations.RunPython.noop),
    ]
