# Generated by Django 5.2.15 on 2026-07-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_purchaserequest_seat_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.car'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='node_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='can_view_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='invite_status',
            field=models.CharField(choices=[('active', 'فعال'), ('invited', 'دعوت\u200cشده'), ('disabled', 'غیرفعال')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='api.portaluser'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='password_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='personnel_code',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.portaluser'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='api_activit_user_id_c1358b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['category', 'created_at'], name='api_activit_categor_5b7d97_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='api_activit_created_6d5a59_idx'),
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.portaluser'),
        ),
    ]
