# Generated by Django 5.2.15 on 2026-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invitetoken_activitylog_car_activitylog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('vehicles', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critical', 'critical')], default='warning', max_length=12)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TrafficStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('endpoint', models.CharField(max_length=80)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('errors_4xx', models.PositiveIntegerField(default=0)),
                ('errors_5xx', models.PositiveIntegerField(default=0)),
                ('total_ms', models.BigIntegerField(default=0)),
                ('max_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['bucket'], name='api_traffic_bucket_cb7e9e_idx')],
                'unique_together': {('bucket', 'endpoint', 'method')},
            },
        ),
        migrations.CreateModel(
            name='VisitorSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('ip_hash', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('day', 'ip_hash')},
            },
        ),
    ]
