# Generated by Django 5.2.15 on 2026-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dataqualityrun_systemalert_trafficstat_visitorseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=True)),
                ('load_threshold', models.FloatField(default=0.55)),
                ('auto_resume', models.BooleanField(default=True)),
                ('embed_rate_pps', models.FloatField(default=1.5)),
                ('diag_secs_per_car', models.FloatField(default=90.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('scheduled', 'scheduled'), ('running', 'running'), ('paused', 'paused'), ('stalled', 'stalled'), ('done', 'done'), ('failed', 'failed'), ('canceled', 'canceled')], db_index=True, default='pending', max_length=16)),
                ('trigger', models.CharField(choices=[('manual', 'manual'), ('auto', 'auto'), ('schedule', 'schedule')], default='manual', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, default='', max_length=120)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('log_tail', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
