# Generated by Django 5.2.15 on 2026-07-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orgrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vehicle_access', 'درخواست دسترسی به خودرو'), ('seats', 'افزایش ظرفیت کاربران'), ('ai_assistant', 'فعال\u200cسازی دستیار هوشمند'), ('documents', 'افزودن بسته مستندات'), ('support', 'پشتیبانی'), ('other', 'سایر')], default='support', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شد'), ('rejected', 'رد شد')], db_index=True, default='pending', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد')], default='normal', max_length=8)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('handled_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(db_index=True, max_length=48)),
                ('audience', models.CharField(choices=[('admin', 'admin'), ('company', 'company'), ('user', 'user'), ('all', 'all')], default='admin', max_length=12)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='orgrole',
            new_name='api_orgrole_company_3ea78d_idx',
            old_name='api_orgrole_company_rank_idx',
        ),
        migrations.AddField(
            model_name='companyrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.company'),
        ),
        migrations.AddField(
            model_name='companyrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to='api.portaluser'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['audience', 'id'], name='api_event_audienc_c34daa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company_id', 'id'], name='api_event_company_d46699_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrequest',
            index=models.Index(fields=['company', 'status'], name='api_company_company_e3d644_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrequest',
            index=models.Index(fields=['status', 'created_at'], name='api_company_status_097f90_idx'),
        ),
    ]
