# Generated by Django 5.2.15 on 2026-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_companyrequest_event_systemstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='app_url',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
