# Generated by Django 5.2.15 on 2026-07-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_activitylog_app_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('brand', models.CharField(blank=True, default='', max_length=40)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('name_filter', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('failed', 'failed'), ('canceled', 'canceled')], db_index=True, default='pending', max_length=12)),
                ('listing', models.JSONField(blank=True, default=list)),
                ('vehicles_total', models.IntegerField(default=0)),
                ('vehicles_done', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('zip_name', models.CharField(max_length=300)),
                ('size', models.BigIntegerField(default=0)),
                ('mtime', models.FloatField(default=0.0)),
                ('brand', models.CharField(blank=True, default='', max_length=40)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('car_name', models.TextField(blank=True, default='')),
                ('stem', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('parsing', 'parsing'), ('done', 'done'), ('failed', 'failed'), ('skipped_duplicate', 'skipped_duplicate')], db_index=True, default='pending', max_length=20)),
                ('pages_processed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='download_secs_per_vehicle',
            field=models.FloatField(default=120.0),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='parse_secs_per_zip',
            field=models.FloatField(default=180.0),
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('sections_used', models.JSONField(blank=True, default=list)),
                ('builder_version', models.CharField(blank=True, default='', max_length=16)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='api.car')),
            ],
        ),
    ]
