# Generated by Django 5.2.15 on 2026-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_downloadrequest_zippackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='max_power',
            field=models.BooleanField(default=False),
        ),
    ]
