# Generated by Django 5.2.15 on 2026-07-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pipelinesettings_max_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_graph', to='api.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.portaluser')),
            ],
        ),
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('canvas_x', models.FloatField(default=0)),
                ('canvas_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.orggraph')),
                ('occupant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat', to='api.portaluser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.orgnode')),
            ],
            options={
                'ordering': ['graph_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NodePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_access', models.JSONField(blank=True, default=list)),
                ('ai_eligible', models.BooleanField(default=False)),
                ('admin_panels', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='api.orgnode')),
            ],
        ),
        migrations.CreateModel(
            name='NodeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.orgnode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['graph', 'parent'], name='api_orgnode_graph_i_82fe7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgnode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root', True)), fields=('graph',), name='one_root_per_graph'),
        ),
    ]
