# Generated by Django 5.2.15 on 2026-07-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_orggraph_orgnode_nodepermission_nodeinvite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='org_role',
        ),
        migrations.DeleteModel(
            name='OrgRole',
        ),
    ]
