# Generated by Django 5.2.15 on 2026-09-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_otpchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=4)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_events', to='api.portaluser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind', 'at'], name='api_otpeven_user_id_ea65c7_idx')],
            },
        ),
    ]
