# Generated by Django 5.2.15 on 2026-09-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_otpevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadRequest',
        ),
    ]
