# Generated by Django 5.2.15 on 2026-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_downloadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(default='login', max_length=8),
        ),
    ]
