# Generated by Django 5.2.15 on 2026-09-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_otpchallenge_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='role',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='api.company')),
            ],
            options={
                'ordering': ['is_builtin', 'created_at'],
                'unique_together': {('company', 'value')},
            },
        ),
    ]
